version: '3.8'

services:
  frontend:
    image: cseazeem/course-management-frontend
    container_name: course_management_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
